language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

install:
  - composer self-update
  - composer create-project --prefer-dist --stability=dev dominus77/yii2-advanced-start
  - git clone https://github.com/Dominus77/yii2-config-db.git modules/config

before_install:
  - sudo pip install codecov

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - composer install --dev

script:
  - php init --env=Development --overwrite=n
  - mysql -e 'CREATE DATABASE yii2_advanced_start_test;'
  - php yii_test migrate --interactive=0
  - php yii_test migrate -p=@modules/config/migrations --interactive=0
  - cd modules/config
  - ../../vendor/bin/codecept run
